name: CICD Database Dev to Prod

on:
  push:
   branches:
    - main

jobs:
  db_cicd:
    name: Database CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout My Code
        uses: actions/checkout@v4  # Checkout ke repository code yang kita gunakan
      - name: SSH Connect
        uses: appleboy/ssh-action@v1 # Digunakan untuk konek ke server melalui SSH
        with:
          host: ${{ secrets.SERVER_HOST }} # IP Address Server
          username: ${{ secrets.SERVER_USER }} # Username SSH
          password: ${{ secrets.SERVER_PASSWORD }} # Password SSH
          script: |
            echo "Berhasil Konek ke Server"
            
            cd /home/yis
            echo "Berhasil Masuk ke Folder YIS"

            docker compose up -d # Menjalankan docker compose di server
            echo "Berhasil Menjalankan Docker Compose"

            # CI (Continuous Integration) untuk Database
            echo "Menunggu Server MySQL Siap"
            sleep 30

            docker exec mysql_devel_container mysql -u root -pTelkom123! -e "SHOW DATABASES;" # Mengecek apakah database sudah siap

            # CD (Continuous Deployment) untuk Database
            echo "DUMP Datbase dari mysql_devel..."
            docker exec mysql_devel_container mysqldump -u root -pTelkom123! --databases academics_devel > /home/yis/academics_devel.sql

            echo "Copy dump ke msqyl_prod..."
            docker cp /home/yis/academics_devel.sql mysql_prod_container:/tmp/academics_devel.sql

            echo "Import dump ke mysql_prod..."
            docker exec mysql_prod_container sh -c 'mysql -u root -pTelkom123! academics < /tmp/academics_devel.sql'

            echo "Berhasil Import Database ke mysql_prod"